### ISSUE TITLE
Inviter

### ISSUE THREAD

**Issue by Hannatrax** [Its-LALOL/Discord-Raid-Tool#2]
When I pressed start, **chrome** started to turn on, but it turned off and on.

**Comment by Its-LALOL** [comment]
`selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:49929
from session not created: This version of ChromeDriver only supports Chrome version 113`

1. Reinstall Raid Tool (i fixed inviter)
2. Update ur chrome browser (chrome://settings/help)
